# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-petclinic
  template:
    metadata:
      labels:
        app: app-petclinic
    spec:
      containers:
      - name: app-petclinic
        image: app-petclinic-image:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "postgres"
        - name: POSTGRES_URL
          value: "jdbc:postgresql://postgres/petclinic"

---
# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-petclinic
spec:
  type: NodePort
  selector:
    app: app-petclinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
