###
# Refresh context
POST http://localhost:8080/actuator/refresh
Content-Type: application/json


###
# Update property
POST http://localhost:8080/actuator/env
Content-Type: application/json
Accept: application/json

{"name":"salary.integration.enabled", "value":"true"}

###
GET http://localhost:8080/vets/6


###
GET http://localhost:8080/actuator/beans

###
GET http://localhost:8080/actuator/env
