CREATE TABLE IF NOT EXISTS vets (
                                  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  first_name TEXT,
                                  last_name  TEXT
);
CREATE INDEX ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
                                         id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name TEXT
);
CREATE INDEX ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
                                             vet_id       INT NOT NULL REFERENCES vets (id),
                                             specialty_id INT NOT NULL REFERENCES specialties (id),
                                             UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
                                   id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name TEXT
);
CREATE INDEX ON types (name);

CREATE TABLE IF NOT EXISTS owners (
                                    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    first_name TEXT,
                                    last_name  TEXT,
                                    address    TEXT,
                                    city       TEXT,
                                    telephone  TEXT
);
CREATE INDEX ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
                                  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name       TEXT,
                                  birth_date DATE,
                                  type_id    INT NOT NULL REFERENCES types (id),
                                  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);

CREATE TABLE IF NOT EXISTS visits (
                                    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    pet_id      INT REFERENCES pets (id),
                                    visit_date  DATE,
                                    description TEXT
);
CREATE INDEX ON visits (pet_id);

-- Align with JPA schema

ALTER TABLE vet_specialties
  ADD CONSTRAINT pk_vet_specialties PRIMARY KEY (specialty_id, vet_id);

ALTER TABLE owners
  ALTER COLUMN address TYPE VARCHAR(255) USING (address::VARCHAR(255));

ALTER TABLE owners
  ALTER COLUMN city TYPE VARCHAR(255) USING (city::VARCHAR(255));

ALTER TABLE visits
  ALTER COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE owners
  ALTER COLUMN first_name TYPE VARCHAR(255) USING (first_name::VARCHAR(255));

ALTER TABLE vets
  ALTER COLUMN first_name TYPE VARCHAR(255) USING (first_name::VARCHAR(255));

ALTER TABLE owners
  ALTER COLUMN last_name TYPE VARCHAR(255) USING (last_name::VARCHAR(255));

ALTER TABLE vets
  ALTER COLUMN last_name TYPE VARCHAR(255) USING (last_name::VARCHAR(255));

ALTER TABLE pets
  ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE specialties
  ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE types
  ALTER COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE owners
  ALTER COLUMN telephone TYPE VARCHAR(255) USING (telephone::VARCHAR(255));

ALTER TABLE pets
  ALTER COLUMN type_id DROP NOT NULL;
